### PR TITLE
Support object cloning and fix runner to be able to use them several times

### PR DESCRIPTION
**Pull request by frenchcomp**
In PHP, objects cloning does not clone objects inside the cloned object ( http://php.net/manual/en/language.oop5.cloning.php )

So, operations on $command2  (with $command2 = clone $command1) affect also $command1.

This pull request adds support of deep cloning.
Fix another issue to use some runner several times (else, firsts outputs are append to next output).

### CODE REVIEW

**Comment by adambrett** [comment]
@frenchcomp Thanks for this. I'm happy to merge it, just a few build errors to fix first.

**Comment by frenchcomp** [comment]
Sorry for the delay, i was very busy these days :)

**Comment by adambrett** [comment]
@frenchcomp thanks for this, and no problem at all on the delay! There's just one last thing: could you remove the docblock comments please? I don't use them anywhere else in the library - the code is simple enough that it should be self explanitory!

Thanks

**Comment by frenchcomp** [comment]
Done :)

**Pull request merged**
