### PR TITLE
Added the `Proc` runner, and tests.

### PR DESCRIPTION
**Pull request by XedinUnknown**
Aims to incorporate solution for issue #7.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
@adambrett, I can see that the checks are failing, but not sure exactly what has to be done for them to pass. Could you tell me what I need to do?

**Comment by smalot** [comment]
I like your job !
About your failing check, I think you should take care of this report:
https://travis-ci.org/adambrett/php-shell-wrapper/jobs/115582567
It reveals that your naming functions and variable is not compliant.
Don't start by '_' and respect camel case.

**Comment by XedinUnknown** [comment]
@smalot, thanks! However, starting the names of `protected` and `private` properties and methods is now a violation of PSR. Why is the check failing on this?

**Comment by smalot** [comment]
Starting properties and methods with an underscore was a convention in PHP4 to separate them between public and protected/private. Now that's an old and bad convention which much be avoid.
I don't which convention engine is used to check this API, but I agree with it about the need to remove any starting underscore.

**Comment by XedinUnknown** [comment]
Starting protected properties and methods with an underscore is a Zend convention, one adopted by engines such as Magento. Furthermore, this does not conflict with PSR-2, as it says [here](http://www.php-fig.org/psr/psr-2/#4-3-methods):
> Method names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

As can indicated by the words "SHOULD NOT", this is not an absolute requirement of the specification.
Particularly with regard to protected methods, this is very useful because it allows defining methods with a similar name but different access.

In any case, I will fix this in the code if this is what's necessary for this pull request to be accepted. Thanks for pointing it out.

**Comment by adambrett** [comment]
Thanks for your hard work @XedinUnknown, it looks like you've made some good progress, this pull request needs simplifying greatly before it can be accepted though. Please take a look at the other task runners and see how little code they have, and how lightweight they are

The other features like the env and working directory I would like to solve in another, more object oriented and universal way that will work for all of the runners, so I would like to see those removed from this PR.

What I'd like to see:

A single `run` method that executes the command, and captures stdout/stderror & return code.

A new interface for `getOutput` (similar to the ReturnValue interface), and adding of this interface to the `Exec` runner, as well as the `Proc` runner (as they both produce output), maybe this interface should be called `StandardOutput`.

A new interface for `getError`, which applies to the `Proc` runner, which returns the output of stderror, maybe called `ErrorOutput`.

Increased test coverage for the proc runner (80%+), which should be easier to achieve with less code.

The callback pattern is interesting, I can see it's use for long running processes, but as PHP is blocking I would question it's viability in a real-world application. I'm not sure I want this baked in to the library, if we were to support it, it should probably be by sub-classing the proc runner in user space, rather than in the library.

If you're happy to take this on, please let me know, otherwise leave this open and I'll take a look at making the necessary changes to your code when I get some time, as it seems a Proc runner is something a lot of people would like.

**Comment by smalot** [comment]
I found this class attached to the PHPBrew library:
https://raw.githubusercontent.com/phpbrew/phpbrew/master/src/PhpBrew/Process.php

**Comment by XedinUnknown** [comment]
Hi All,
And sorry for the delayed reply. While I have never had the desire to explain why there's no better way to do this, right now I at least have the time.

In short, this is the only way to do this with `proc_open()`. All other runners use functions of PHP that do not provide all the details and flexibility of the actual process. Summary:

- [`Exec`](https://github.com/adambrett/php-shell-wrapper/blob/master/src/Runners/Exec.php): Using [`exec()`](http://php.net/manual/en/function.exec.php) does not allow you to get error output. Also, can't give input, or supply a stream to write to. Additionally, cannot execute process in a directory different to PHP's CWD, or supply any environment variables.
- [`Passthru`](https://github.com/adambrett/php-shell-wrapper/blob/master/src/Runners/Passthru.php): Using [`passthru()`](http://php.net/manual/en/function.passthru.php) has the same exact problem as Exec.
- [`ShellExec`](https://github.com/adambrett/php-shell-wrapper/blob/master/src/Runners/ShellExec.php): Using [`shell_exec()`](http://php.net/manual/en/function.shell-exec.php) has the same disadvantages as `exec()`, and also cannot get return value.
- [`System`](https://github.com/adambrett/php-shell-wrapper/blob/master/src/Runners/System.php): Using [`system()`](https://github.com/adambrett/php-shell-wrapper/blob/master/src/Runners/System.php) has all the disadvantages of `passthru()`, but returns the last line of output.

As you can see, most PHP's shell-invoking functions are absolutely miserable, and don't allow you to do what you need, if you need to simply run a command, get it's output *including error output* and obtain the result value. Of course, with anything more complex, such as piping, there is absolutely no chance. Luckily, I didn't need to do anything complex. So, I made an OO wrapper for the `proc_*()` family. If you had tried using it, you would know that it, however, is nowhere as simple as using any of the above. Let's look at the signature of [`proc_open()`](http://php.net/manual/en/function.proc-open.php):

1. *`string $cmd`* - The command. All is obvious here.
2. *`array $descriptorspec`* - Took me an hour just to understand what this is. This is the description of all the pipes, input and output, that the process will use. Obtaining error output is mission critical for me.
3. *`array &$pipes`* - Resources will be created from the descriptors of `$descriptorspec`, corresponding to them by index.
4. *`string $cwd`* - Allows you to execute the process in an arbitrary directory. Fantastic! This is very beneficial for me.
5. *`array $env`* - Allows you to specify, including overriding, any environment variables for the process. Amazing! This is mission-critical for me.
6. *`array $other_options`* - Windows-specific stuff.

As you can see, there's no way to just execute a command, and be done with it. Output has to be read from created resources. If you constantly try to read, it will eat all the processing cycles, so need an "intelligent" sleep pattern. Obtaining the return value is unreliable due to the async nature of the process, so a workaround needs to be implemented.

So, here I present to you a highly adapted and normalized OO wrapper for the most complicated method. It is documented, implements the required interfaces, and is ready to be *used* in the simple way that you intend: pass command, get output and return value. If you think it can be done simpler, please go ahead and give it a try.

**Comment by adambrett** [comment]
Will do, thanks

**Pull request closed without merging**
